### ISSUE TITLE
Research patching disabling certificate validation

### ISSUE THREAD

**Issue by xadamxk** [xadamxk/LCU-Enhancement-Suite#33]
In connection.ts we disabled certificate validation in order to get an active connection to the LCU connection.
Is it possible to use a local certificate to prevent this?

```
      options.agent = new Agent({
        rejectUnauthorized: false
      });
```

**Comment by TyrantKingBen** [comment]
The CA and LoL-client certificate appear to only be embedded in the executables: `LeagueClient.exe` and `LeagueClientUx.exe`.
