### ISSUE TITLE
League Client - Custom HTML Requests to Change Status/Profile Banner/ProfilePicture/Chat Rank

### ISSUE THREAD

**Issue by HerXayah** [xadamxk/LCU-Enhancement-Suite#39]
- as title says.

If needed ill explain further

**Comment by xadamxk** [comment]
Could you provide an example or use case so I can better understand what you are asking for?

I assume you mean custom assets on your profile, but I'd like to be sure.

**Comment by HerXayah** [comment]
https://github.com/Everkers/moon-slayer

Like here to change the Champion on your Profile and set a custom Status, BUT not Over UI but over rightklicking the Icon in Taskbar and selecting it from a list Context Menu

**Comment by xadamxk** [comment]
#47 and #48 are now implemented on the master branch.

**Comment by xadamxk** [comment]
#50 #51 #52 Are considered enhancements that require further research and are added to the backlog.
