### ISSUE TITLE
Implement release-it 

### ISSUE THREAD

**Issue by HerXayah** [xadamxk/LCU-Enhancement-Suite#40]
Implement https://github.com/release-it/release-it to make it easier for Users to install this App.
So they dont need to build it themselves and its autodone on Update

**Comment by xadamxk** [comment]
This is the last step for version 1. I don't want to include an executable until features have been thoroughly tested.

**Comment by xadamxk** [comment]
Rather than release-it we used electron builder with github actions.

Thank you for the suggestion!
