### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by yrir** [xadamxk/LCU-Enhancement-Suite#69]
Windows 11 21H2 (22000.318)

Error Info：
A JavaScript error occurred in the main process 
Uncaught Exception:
Error: connect ECONNREFUSED 127.0.0.1:64940
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1134:16)

**Comment by xadamxk** [comment]
Do you have another windows machine that isn't on Windows 11?
I do not, so debugging this might be tough.
